# Generated by Django 5.2 on 2025-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(null=True, verbose_name="마지막 로그인"),
        ),
    ]
