# Generated by Django 5.2 on 2025-05-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="post_images/%Y/%m/%d/"
            ),
        ),
    ]
