# Generated by Django 5.2 on 2025-05-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "게시물",
                "verbose_name_plural": "게시물",
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="삭제일"),
        ),
        migrations.AlterField(
            model_name="post",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="삭제자",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/post_images/%Y/%m/%d/",
                verbose_name="이미지",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="이미지 URL"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="삭제 여부"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
