# Generated by Django 5.2 on 2025-05-12 02:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("like", "0003_alter_like_post"),
        ("post", "0003_alter_post_options_remove_post_likes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_posts",
                through="like.Like",
                to=settings.AUTH_USER_MODEL,
                verbose_name="좋아요",
            ),
        ),
    ]
