# Generated by Django 5.2 on 2025-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_deleted_at_post_deleted_by_post_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="post_commen_parent__963303_idx",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/%d/"),
        ),
    ]
