# Generated by Django 5.2 on 2025-04-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_remove_comment_post_commen_parent__963303_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
