# Generated by Django 5.2 on 2025-05-12 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("like", "0001_initial"),
        ("post", "0003_alter_post_options_remove_post_likes_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="post.post",
                verbose_name="게시글",
            ),
        ),
    ]
