# Generated by Django 5.2 on 2025-05-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("like", "0002_alter_like_unique_together_alter_like_post"),
        ("post", "0003_alter_post_options_remove_post_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="post.post",
                verbose_name="게시글",
            ),
        ),
    ]
