# Generated by Django 5.2 on 2025-05-13 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("like", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="콘텐츠 타입",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="object_id",
            field=models.PositiveIntegerField(null=True, verbose_name="객체 ID"),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
