# Generated by Django 5.2 on 2025-05-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idol", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idol",
            name="en_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
