# Generated by Django 5.2 on 2025-05-13 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idol", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="idol",
            name="managers",
            field=models.ManyToManyField(
                blank=True, related_name="managed_idols", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
