# Generated by Django 5.2 on 2025-05-14 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idol", "0002_idol_managers"),
        ("idol_schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="idol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="idol.idol",
            ),
        ),
        migrations.DeleteModel(
            name="Idol",
        ),
    ]
